sudo: false
language: python
python:
  - "2.7"
script:
  - mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: site
  on:
    branch: master

env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL=isaacvetter@gmail.com
    #- ENCRYPTION_LABEL=ddaacfe268bd

notifications:
  webhooks:
    - https://chat.fhir.org/api/v1/external/travis?stream=fhircast-committers&topic=ci-notifications&api_key=abyE3VEEndMrLJEJCqwbgkQWQTJWq4AQ
