site_name: FHIRcast
nav:
    - Home: index.md
    - Specification: 
        - '1.0': 'specification/1.0.md'
    - Launch Scenarios: launch-scenarios.md
    - Security Considerations: security-considerations.md
    - About: about.md
theme: readthedocs
